---
# Add this snippet to the top of your playbook. 
# It will install python2 if missing (but checks first so no expensive repeated apt updates)
# gwillem@gmail.com

- hosts: tag_role_ag-bie
  gather_facts: False
  become: yes
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal && wget https://bootstrap.pypa.io/get-pip.py &&  python get-pip.py &&  pip install boto && pip install boto3)


# Gather facts about a particular ELB
- hosts: localhost
  connection: local
  tags:
      - configuration
  tasks:
  - elb_application_lb_facts:
      names: "{{ env_name }}-elb"
      region: ap-southeast-2
    register: elb_facts

- hosts: tag_role_ag-bie
  gather_facts: no
  tags:
      - configuration
  tasks:
  - set_fact:
      elb_dns: "{{ hostvars.localhost.elb_facts.load_balancers[0].dns_name }}"
    when: hostvars.localhost.elb_facts.load_balancers.0 is defined

- hosts: tag_role_ag-bie
  gather_facts: False
  become: yes
  tasks:
    - include: ../ag-bie/ansible/ag-bie.yml