---
- name: update hosts file with fqdn
  lineinfile: path=/etc/hosts line="127.0.0.1 {{ server_name }}" regexp=line="127.0.0.1 {{ server_name }}" state=present

- name: Stop jenkins service
  service: name=jenkins state=stopped
  
- name: Make sure folder /data/work/nsl is created with right permissions
  file: path=/data/work/nsl state=directory owner=jenkins mode=0755

- name: Make sure folder /data/work/taxaas is created with right permissions
  file: path=/data/work/taxaas state=directory owner=jenkins mode=0755

- name: Make sure folder /data/work/TaxxaS is created with right permissions
  file: path=/data/work/TaxxaS state=directory owner=jenkins mode=0755

- name: update the jenkins args in the jenkins config file
  lineinfile: path="/etc/default/jenkins" line='JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --prefix=$PREFIX"' regexp='^JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --prefix=$PREFIX"' state=present

- name: Make sure folder /etc/nginx/ssl is created with right permissions
  file: path=/etc/nginx/ssl state=directory owner=root mode=0755

- name: Copy ssl certificate to nginx conf directory and rename
  copy: src=./pki/certificate.pem dest="/etc/nginx/ssl/{{server_name}}.self.crt" mode=644

- name: Copy the key file to the nginx conf dir and rename
  copy: src=./pki/key.pem dest="/etc/nginx/ssl/{{server_name}}.self.key" mode=400

- name: Remove existing nginx configuration
  command: bash -c "mv /etc/nginx/sites-available/{{server_name}}.conf /etc/nginx/sites-available/{{server_name}}.conf.bak"

- name: Copy new nginx configuration
  template: src=nginx-jenkins-vhost.conf.j2 dest="/etc/nginx/sites-available/{{server_name}}.conf"

- name: Start jenkins service
  service: name=jenkins state=started

- name: Restart nginx service
  service: name=jenkins state=restarted